image: alpine/edge
secrets:
  - 88cce185-d2ec-4573-9546-e33f36f79bbf
sources:
  - git+ssh://git@git.sr.ht/~swaits/glicko2
tasks:
  - mirror-to-github: |
      cd ~/glicko2
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:swaits/glicko2.git
      git push --mirror github
